apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-to-sync-config
data:
  MYSQL_TO_ASYNC_HTTP_HOST: "0.0.0.0"
  MYSQL_TO_ASYNC_HTTP_PORT: "8080"

  MYSQL_TO_ASYNC_DATASOURCE_PROVIDER: "mysql"
  MYSQL_TO_ASYNC_DATASOURCE_HOST: "mysql-source"
  MYSQL_TO_ASYNC_DATASOURCE_PORT: "3306"
  MYSQL_TO_ASYNC_DATASOURCE_DATABASE: "source_db"
  MYSQL_TO_ASYNC_DATASOURCE_DEBUG: "false"

  MYSQL_TO_ASYNC_TARGET_HOST: "mysql-target"
  MYSQL_TO_ASYNC_TARGET_PORT: "3306"
  MYSQL_TO_ASYNC_TARGET_DATABASE: "target_db"

  MYSQL_TO_ASYNC_REDIS_HOST: "redis"
  MYSQL_TO_ASYNC_REDIS_PORT: "6379"
  MYSQL_TO_ASYNC_REDIS_DB: "0"

  MYSQL_TO_ASYNC_STORAGE_MODE: "file"
  MYSQL_TO_ASYNC_STORAGE_DATA_DIR: "/app/data"

  MYSQL_TO_ASYNC_LOG_LEVEL: "info"
  MYSQL_TO_ASYNC_LOG_CONSOLE_ENABLE: "true"
  MYSQL_TO_ASYNC_LOG_CONSOLE_NO_COLOR: "true"
  MYSQL_TO_ASYNC_LOG_FILE_ENABLE: "true"
